#!/usr/bin/env bash

set -e
clear

APPNAME='ntpc'
PACKAGE="go.hansaray.pw/${APPNAME}"

cd $( dirname -- "$0"; );
ROOTDIR=$PWD;

VERSION="$(git describe --tags --always --abbrev=0 --match='v[0-9]*.[0-9]*.[0-9]*')"
COMMIT_HASH="$(git rev-parse --short HEAD)"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
BUILD_TIME=$(date '+%Y-%m-%dT%H:%M:%S')
BUILD_USER=$(id -u -n)

LDFLAGS=("-s -w "
  "-X '${PACKAGE}/version.AppName=${APPNAME}'"
  "-X '${PACKAGE}/version.Version=${VERSION}'"
  "-X '${PACKAGE}/version.CommitHash=${COMMIT_HASH}'"
  "-X '${PACKAGE}/version.BuildTime=${BUILD_TIME}'"
  "-X '${PACKAGE}/version.UserName=${BUILD_USER}'"
)

# Remember Go env settings, so we can set them back
GOMOD=$(go env GO111MODULE)
GOCGO=$(go env CGO_ENABLED)

echo "[INF] LDFLAGS: ${LDFLAGS[*]}"

echo "[INF] setting build env"
export GO111MODULE="off"
go env -w CGO_ENABLED=0
go env -w GO111MODULE=off

# Just edit: Title, Description, and Tags
metadata() {
    echo '# Do not edit this file here, see make.sh' > metadata.toml
    echo "Name = '${APPNAME}'" >> metadata.toml 
    echo "Version = '${VERSION}'" >> metadata.toml 
    echo "Package = '${PACKAGE}'" >> metadata.toml 
    echo "Repo = 'https://github.com/gotamer/${APPNAME}'" >> metadata.toml 
    echo "Branch = '${BRANCH}'" >> metadata.toml 
    echo "Homepage = 'http://${PACKAGE}'" >> metadata.toml 
    echo "Title = 'NTP Client'" >> metadata.toml 
    echo 'Description = "Simple NTP client"' >> metadata.toml 
    echo "Documentation = 'https://pkg.go.dev/${PACKAGE}'" >> metadata.toml 
    echo 'Tags = ["ntp","ntpc","RFC5905","client","golang"]' >> metadata.toml 
    echo 'License = "MIT"' >> metadata.toml 
}

dirBin() {
	if [ ! -d "$GOBIN" ]; then
		GOBIN="${ROOTDIR}/bin"
		mkdir -p "${ROOTDIR}/bin"
	fi
	if [ ! -d "$DIRBIN" ]; then
		DIRBIN="${ROOTDIR}/bin"
		mkdir -p "${ROOTDIR}/bin"
	fi
	echo "[INF] GOBIN: $GOBIN"
	echo "[INF] DIRBIN: $DIRBIN"
}

fmt() {
	echo "[INF] fmt ${APPNAME}"
	go fmt "${ROOTDIR}"
}

build() {
	fmt
	wait
	echo "[INF] build & install ${APPNAME}"
	dirBin
	wait
	go build -o="${GOBIN}" -ldflags="${LDFLAGS[*]}" 
	wait
	echo "[INF] ${APPNAME} at ${GOBIN}"	
}

release() {
	# go tool dist list | grep linux
	echo "[INF] release, fmt, metadata, and build to: /tmp/${APPNAME}"
	fmt
	wait
	dirBin
	wait
	env GOOS=linux GOARCH=386 go build -o="${DIRBIN}/${APPNAME}-linux-386" -ldflags="${LDFLAGS[*]}" 
	wait
	env GOOS=linux GOARCH=amd64 go build -o="${DIRBIN}/${APPNAME}-linux-amd64" -ldflags="${LDFLAGS[*]}" 
	wait
	env GOOS=linux GOARCH=arm GOARM=6 go build -o="${DIRBIN}/${APPNAME}-linux-arm6" -ldflags="${LDFLAGS[*]}" 
	wait
	env GOOS=linux GOARCH=arm GOARM=7 go build -o="${DIRBIN}/${APPNAME}-linux-arm7" -ldflags="${LDFLAGS[*]}" 
	wait
	env GOOS=linux GOARCH=arm64 go build -o="${DIRBIN}/${APPNAME}-linux-arm64" -ldflags="${LDFLAGS[*]}" 
	wait
	env GOOS=linux GOARCH=mips go build -o="${DIRBIN}/${APPNAME}-linux-mips" -ldflags="${LDFLAGS[*]}" 
	wait
	env GOOS=linux GOARCH=mips64 go build -o="${DIRBIN}/${APPNAME}-linux-mips64" -ldflags="${LDFLAGS[*]}" 
	wait
	env GOOS=linux GOARCH=riscv64 go build -o="${DIRBIN}/${APPNAME}-linux-riscv64" -ldflags="${LDFLAGS[*]}" 
	wait
	env GOOS=freebsd GOARCH=amd64 go build -o="${DIRBIN}/${APPNAME}-freebsd-amd64" -ldflags="${LDFLAGS[*]}" 
	wait
}

all() {
    metadata
	wait
	build
	wait
	release
	wait
}
# executes the function $1 $2 $3 $4 $5 are the arguments
$@

# Wait for the functions to finish
wait

echo "[INF] setting Go env back to:"
echo "[INF] GOARCH=$(go env GOHOSTARCH) GOOS=$(go env GOHOSTOS) GO111MODULE=${GOMOD} GOCGO=${GOCGO}"
go env -w GOARCH=$(go env GOHOSTARCH) 
go env -w GOOS=$(go env GOHOSTOS) 
go env -w CGO_ENABLED=${GOCGO}
go env -w GO111MODULE=${GOMOD}
echo "[INF] all done"
